src/Entity/MooveeCar.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MooveeCarRepository")
 */
class MooveeCar
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $brand_car;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $model_car;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $is_deleted;


    /**
     * @ORM\Column(type="string", length=200)
     */
    private $category_car;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MooveeUserHasCar", mappedBy="user_has_car_id_car")
     */
    private $mooveeUserHasCars;



    public function __construct()
    {
        $this->mooveeUserHasCars = new ArrayCollection();

    }





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrandCar(): ?string
    {
        return $this->brand_car;
    }

    public function setBrandCar(string $brand_car): self
    {
        $this->brand_car = $brand_car;

        return $this;
    }

    public function getModelCar(): ?string
    {
        return $this->model_car;
    }

    public function setModelCar(string $model_car): self
    {
        $this->model_car = $model_car;

        return $this;
    }

    public function getIsDeleted(): ?int
    {
        return $this->is_deleted;
    }

    public function setIsDeleted(?int $is_deleted): self
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }


    public function getCategoryCar(): ?string
    {
        return $this->category_car;
    }

    public function setCategoryCar(string $category_car): self
    {
        $this->category_car = $category_car;

        return $this;
    }

    /**
     * @return Collection|MooveeUserHasCar[]
     */
    public function getMooveeUserHasCars(): Collection
    {
        return $this->mooveeUserHasCars;
    }

    public function addMooveeUserHasCar(MooveeUserHasCar $mooveeUserHasCar): self
    {
        if (!$this->mooveeUserHasCars->contains($mooveeUserHasCar)) {
            $this->mooveeUserHasCars[] = $mooveeUserHasCar;
            $mooveeUserHasCar->setUserHasCarIdCar($this);
        }

        return $this;
    }

    public function removeMooveeUserHasCar(MooveeUserHasCar $mooveeUserHasCar): self
    {
        if ($this->mooveeUserHasCars->contains($mooveeUserHasCar)) {
            $this->mooveeUserHasCars->removeElement($mooveeUserHasCar);
            // set the owning side to null (unless already changed)
            if ($mooveeUserHasCar->getUserHasCarIdCar() === $this) {
                $mooveeUserHasCar->setUserHasCarIdCar(null);
            }
        }

        return $this;
    }




}

src/Controller/CleanerController.php
<?php

namespace App\Controller;

use App\Entity\MooveeUsers;
use App\Entity\Planing;
use App\Entity\PlannedCleaning;
use App\Form\HorraireType;
use App\Mail\CalendarGoogle;
use App\Repository\MooveeUsersRepository;
use App\Repository\PlaningRepository;
use App\Repository\PlannedCleaningRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;




/**
 * This controller is for planned services "Dashboard : section Planning
 * index : list of all planned services showing in the calendar
 * detail : show a detail of the clicked planned service
 * edit : edit a date of planned service
 * deleteorder : delete planned service
 * add : add a worker to a clicked service
 * delete : delete from table Planning
 */

/**
 * @Route("/cleaner", name="cleaner_")
 * @Security("has_role('ROLE_WORKER')")
 */
class CleanerController extends AbstractController
{

    private $plannedCleaningRepository;
    private $planingRepository;
    private $mooveeUsersRepository;

    public function __construct(PlannedCleaningRepository $plannedCleaningRepository, PlaningRepository $planingRepository, MooveeUsersRepository $mooveeUsersRepository)
    {
        $this->plannedCleaningRepository = $plannedCleaningRepository;
        $this->planingRepository = $planingRepository;
        $this->mooveeUsersRepository = $mooveeUsersRepository;
    }

    /**
     * @Route("/", name="calendar")
     */
    public function index()
    {
        $user =  $this->getUser();
        if ($this->isGranted('ROLE_ADMIN')) {
            $planing = $this->plannedCleaningRepository->findBy(['valide' => null, 'supprime' => null]);
        } elseif ($this->isGranted('ROLE_WORKER_ADMIN')) {
            $planing = $this->plannedCleaningRepository->findBy(['Provider' => $user->getProvider(), 'valide' => null, 'supprime' => null]);
        } else {
            $planing = $this->planingRepository->findBy(['user' => $user->getId(), 'supprime' => null]);
        }
        $plannings= array();
       foreach($planing as $p){
           $time = $this->calculeFromTo($p->getPlannedStart(), $p->getPlannedEnd());
           array_push($plannings, [$p, 'start' => $time[0][0], 'end' => $time[0][1]]);

       }

        return $this->render('cleaner/index.html.twig', [
            'plannings' => $plannings
        ]);
    }
    public function calculeFromTo($from, $to)
  {

    $array = array();

    $minstart = "";
    if ($from % 60 < 10) {
        $minstart = "0";
    }
    $minstart .= $from % 60;
    $minend = "";
    if ($to % 60 < 10) {
        $minend = "0";
    }
    $minend .= $to % 60;
    //case hour < 10
    if(floor($from / 60)%24 < 10)
    {
        $from = "0" . floor($from / 60) . ":" . $minstart;
    }
    else
    {
        $from = floor($from / 60) . ":" . $minstart;
    }
    if(floor($to / 60)%24 < 10)
    {
        $to = "0" . floor($to / 60) . ":" . $minend;
    }
    else
    {
        $to = floor($to / 60) . ":" . $minend;
    }
    array_push($array, [$from, $to]);

    return $array;
  }


    /**
     * @Route("/detail/{id}", name="detail")
     */
    public function detail(int $id)
    {
        return $this->render('cleaner/detail.html.twig', [
            'planing' => $this->plannedCleaningRepository->findOneBy([
                'id' => $id
            ]),
            'workers' => $this->planingRepository->findBy(['PlannedCleaning' => $id])
        ]);
    }

    /**
     * @Route("/detail/{id}/edit", name="edit")
     */
    public function edit(int $id, Request $request)
    {

        $user = $this->getUser();
        $em = $this->getDoctrine()->getManager();
        $cleaning = $this->plannedCleaningRepository->findOneBy(['id' => $id]);

        $form = $this->createForm(HorraireType::class, $cleaning);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $start = ($form["from"]->getData()->format('i')) + ($form["from"]->getData()->format('H') * 60);
            $end = ($form["to"]->getData()->format('i')) + ($form["to"]->getData()->format('H') * 60);

            $cleaning->setPlannedStart($start);
            $cleaning->setPlannedEnd($end);
            $cleaning->setEdited(1);

            $em->flush();
            $this->addFlash('success', 'The date has been successfully edited');
            return $this->redirectToRoute('cleaner_detail', array('id' => $id));
        }

        return $this->render('cleaner/edit.html.twig', [
            'id' => $id,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/detail/{id}/add", name="add")
     * @Security("has_role('ROLE_WORKER_ADMIN')")
     */
    public function add(int $id, Request $request)
    {
        $user =  $this->getUser();
        $planing = $this->plannedCleaningRepository->findOneBy(['id' => $id]);

        $task = new Planing();

        $form = $this->createFormBuilder($task)
            ->add('user', EntityType::class, [
                'class' => MooveeUsers::class,
                'label' => 'Worker',
                'choices' => $this->mooveeUsersRepository->findUserByProvider($planing->getProvider()),
                'choice_label' => function (MooveeUsers $user) {
                    return $user->getFirstname() . ' ' . $user->getLastName();
                },
            ])

            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $task = $form->getData();

            $task->setPlannedCleaning($planing);
            $em = $this->getDoctrine()->getManager();
            $em->persist($task);
            $em->flush();
            return $this->redirectToRoute('cleaner_detail', array('id' => $id));
        }

        return $this->render('cleaner/add.html.twig', [
            'form' => $form->createView(),
            'id' => $id,

        ]);
    }

    /**
     * @Route("/detail/{id}/delete", name="delete_order")
     */
    public function deleteorder(int $id)
    {
        $this->addFlash('success', 'The order has been successfully deleted!');
        $em = $this->getDoctrine()->getManager();

        $delorder = $em->getRepository(PlannedCleaning::class)->find($id);

        $providers = $this->mooveeUsersRepository->findAdminWorkerByProvider($delorder->getProvider());

        try {
            if ($providers != null) {
                foreach ($providers as $provider) {
                    $googleToken = $provider->getGoogleToken();
                    if ($googleToken != null) {
                        $googleCalendar = new CalendarGoogle();
                        $client = $googleCalendar->getClient();
                        $client->setAccessToken($googleToken);
                        $googleCalendar->delete($client, $delorder->getId());
                    }
                }
            }
            $user = $this->getUser();
            $googleToken = $user->getGoogleToken();
            if ($googleToken != null) {

                $googleCalendar = new CalendarGoogle();
                $client = $googleCalendar->getClient();
                $client->setAccessToken($googleToken);
                $googleCalendar->delete($client, $delorder->getId());
            }
        } catch (\Exception $e) {
            $this->addFlash('success', 'The order has been successfully deleted! But we couldn\'nt delete a event from your calendar');
        }

        $planings = $delorder->getPlanings();

        foreach ($planings as $planing) {

            $em->remove($planing);
        }

        $delorder->setSupprime(1);

        $em->flush();

        return $this->redirectToRoute('cleaner_calendar');
    }


    /**
     * @Route("/detail/{id}/delete/{iduser}", name="delete")
     * @Security("has_role('ROLE_WORKER_ADMIN')")
     */
    public function delete(int $id, int $iduser)
    {

        $em = $this->getDoctrine()->getManager();
        $planing = $em->getRepository(Planing::class)->findOneBy(['PlannedCleaning' => $id, 'user' => $iduser]);

        $em->remove($planing);
        $em->flush();
        return $this->redirectToRoute('cleaner_detail', array('id' => $id));
    }
}

templates/cleaner/add.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette{% endblock %}

{% block content %}
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">

            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{{ path("cms_dashboard") }}">Dashboard</a></li>
                        <li><a href="{{ path("cleaner_calendar") }}">Planning</a></li>
                        <li><a href="{{ path("cleaner_detail", {'id': id}) }}">Detail</a></li>
                        <li class="active">Add Car</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content mt-3">
    <div class="animated fadeIn">
    <div class="row">

    <div class="col-md-12">
    <div class="card">
    <div class="card-header">
        <strong class="card-title">Add Car</strong>
    </div>
    <div class="card-body">
    <div class="tile col-lg-4" >



        {{ form_start(form) }}
        <div class="form-group">
            {{ form_errors(form.user) }}
            {{ form_label(form.user) }}
            {{ form_widget(form.user, {'attr':{'class': 'form-control' }}) }}
        </div>




        <button type="submit" class="btn btn-info">Add</button>
        <a href="{{ path("cleaner_detail", {'id': id}) }}"  class="btn btn-danger">Return</a>

        {{ form_end(form) }}

    </div>
    <script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
  	<script src="{{asset('vendors/popper.js/dist/umd/popper.min.js')}}"></script>
  	<script src="{{asset('vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
  	<script src="{{asset('assets/js/main.js')}}"></script>
{% endblock %}

templates/cleaner/detail.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette{% endblock %}

{% block content %}
<div class="breadcrumbs">
    <div class="col-sm-4">
        <div class="page-header float-left">

        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li><a href="{{ path("cms_dashboard") }}">Dashboard</a></li>
                    <li><a href="{{ path("cleaner_calendar") }}">Planning</a></li>
                    <li class="active">Details</li>
                </ol>
            </div>
        </div>
    </div>
</div>

    <div class="content mt-3">
        <div class="animated fadeIn">
            <div class="row">
                <div class="col-lg-4 offset-md-4">
                    <div class="card">
                        <div class="card-header">
                            <strong class="card-title">Description</strong>
                        </div>
                        <div class="card-body">

                            <table class="table table-striped">
                                <tbody>
                                <tr>
                                    <td>User</td>
                                    <td>{{ planing.userId.FirstName|capitalize }} {{ planing.userId.LastName|capitalize }}</td>
                                </tr>
                                <tr>
                                    <td>Email Address</td>
                                    <td>{{ planing.userId.email }}</td>
                                </tr>
                                <tr>
                                    <td>Phone Number</td>
                                    <td>{{ planing.userId.phoneNumber }}</td>
                                </tr>
                                {% if planing.userCarId != null %}
                                    <tr>
                                        <td>Plaque</td>
                                        <td>{{ planing.userCarId.userHasCarNicknameCar|capitalize }}</td>
                                    </tr>
                                    <tr>
                                        <td>Voiture</td>
                                        <td>{{ planing.userCarId.UserHasCarIdCar.brandCar }} {{ planing.userCarId.UserHasCarIdCar.modelCar }} </td>
                                    </tr>
                                    {% if planing.userCarId.spaceNumber != null and planing.userCarId.spaceNumber != "" %}
                                    <tr>
                                        <td>Parking Space Number</td>
                                        <td>{{ planing.userCarId.spaceNumber }}</td>
                                    </tr>
                                    {% endif %} 
                                {% endif %}

                                <tr>
                                    <td>Date</td>
                                    <td>{{ planing.date|date('Y-m-d') }}:   {{ planing.plannedStart|date('i:s') }}/{{ planing.plannedEnd|date('i:s') }}</td>
                                </tr>
                                <tr>
                                    <td>Produit</td>
                                    <td>{{ planing.produit.name }}</td>
                                </tr>
                                <tr>
                                    <th>Option</td>
                                    <td><ul>
                                            {% for option in planing.PlannedCleaningOptions %}
                                                <li>{{ option.optionId.name }}</li>
                                            {% endfor %}
                                        </ul></td>
                                </tr>
                                    {% if is_granted('ROLE_WORKER_ADMIN') %}
                                        <td>Worker</td>
                                        <td><ul>
                                                {% for worker in workers %}
                                                    <li>{{ worker.user.firstName }} {{ worker.user.LastName }}
                                                        <a onclick="return confirm('DO you really want to delete this worker?')" href="{{ path("cleaner_delete", {'id': planing.id , 'iduser':worker.user.id}) }}" class="btn btn-danger btn-sm">
                                                            <i class="fa fa-trash-o mr-0"></i>
                                                        </a>
                                                    </li>

                                                {% endfor %}

                                        </ul>
                                    {% endif %}
                                </tbody>
                            </table>
                            {% if is_granted('ROLE_WORKER_ADMIN') %}
                                <a href="{{ path("cleaner_add", {'id': planing.id }) }}"  class="btn btn-success">Add Worker</a>
                                <a href="{{ path("cleaner_edit", {'id': planing.id }) }}"  class="btn btn-info">Edit</a>
                            {% endif %}
                            {% if is_granted('ROLE_ADMIN') %}
                                <a onclick="return confirm('Do you really want to delete this order?')" href="{{ path("cleaner_delete_order", {'id': planing.id }) }}"  class="btn btn-danger">Delete</a>
                            {% endif %}
                            <a href="{{ path("cleaner_calendar") }}"  class="btn btn-danger">Return</a>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>

    <script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
  	<script src="{{asset('vendors/popper.js/dist/umd/popper.min.js')}}"></script>
  	<script src="{{asset('vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
  	<script src="{{asset('assets/js/main.js')}}"></script>







    <script>
        function time_convert(num)
        {
            var hours = Math.floor(num / 60);
            var minutes = num % 60;
            return hours + ":" + minutes;
        }
    </script>

{% endblock %}

templates/cleaner/edit.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette{% endblock %}

{% block content %}
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">

            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{{ path("cms_dashboard") }}">Dashboard</a></li>
                        <li><a href="{{ path("cleaner_calendar") }}">Planning</a></li>
                        <li><a href="{{ path("cleaner_detail", {'id': id}) }}">Detail</a></li>
                        <li class="active">Add Car</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content mt-3">
    <div class="animated fadeIn">
    <div class="row">

    <div class="col-md-12">
    <div class="card">
    <div class="card-header">
        <strong class="card-title">Edit Order</strong>
    </div>
    <div class="card-body">
    <div class="tile col-lg-4" >



        {{ form_start(form) }}
        <div class="form-group">
            {{ form_errors(form.from) }}
            {{ form_label(form.from) }}
            {{ form_widget(form.from, {'attr':{'class': 'form-control' }}) }}
        </div>
        <div class="form-group">
            {{ form_errors(form.to) }}
            {{ form_label(form.to) }}
            {{ form_widget(form.to, {'attr':{'class': 'form-control' }}) }}
        </div>
        <div class="form-group">
            {{ form_errors(form.date) }}
            {{ form_label(form.date) }}
            {{ form_widget(form.date, {'attr':{'class': 'form-control' }}) }}
        </div>




        <button type="submit" class="btn btn-info">Edit</button>
        <a href="{{ path("cleaner_detail", {'id': id}) }}"  class="btn btn-danger">Return</a>

        {{ form_end(form) }}

    </div>
    <script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
  	<script src="{{asset('vendors/popper.js/dist/umd/popper.min.js')}}"></script>
  	<script src="{{asset('vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
  	<script src="{{asset('assets/js/main.js')}}"></script>
{% endblock %}

templates/cleaner/index.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette
{% endblock %}

{% block content %}
	<style>

		body {
			font-size: 14px;
			font-family: "Helvetica Nueue", Arial, Verdana, sans-serif;
			background-color: #DDDDDD;
		}

		#wrap {
			width: 1100px;
			margin: 0 auto;
		}

		#external-events {
			float: left;
			width: 150px;
			padding: 0 10px;
			text-align: left;
		}

		#external-events h4 {
			font-size: 16px;
			margin-top: 0;
			padding-top: 1em;
		}

		.external-event {
			/* try to mimick the look of a real event */
			margin: 10px 0;
			padding: 2px 4px;
			background: #3366CC;
			color: #fff;
			font-size: 0.85em;
			cursor: pointer;
		}

		#external-events p {
			margin: 1.5em 0;
			font-size: 11px;
			color: #666;
		}

		#external-events p input {
			margin: 0;
			vertical-align: middle;
		}

		#calendar {
			/* 		float: right; */
			margin: 0 auto;
			width: 900px;
			background-color: #FFFFFF;
			border-radius: 6px;
			box-shadow: 0 1px 2px #C3C3C3;
		}
	</style>
	<div class="breadcrumbs">
		<div class="col-sm-4">
			<div class="page-header float-left"></div>
		</div>
		<div class="col-sm-8">
			<div class="page-header float-right">
				<div class="page-title">
					<ol class="breadcrumb text-right">
						<li>
							<a href="{{ path("cms_dashboard") }}">Dashboard</a>
						</li>
						<li class="active">Cleaner</li>
					</ol>
				</div>
			</div>
		</div>
	</div>

	<div class="content mt-3">
		<div class="animated fadeIn">
			<div id='wrap'>

				<div id='calendar'></div>

				<div style='clear:both'></div>

			</div>
		</div>
		<!-- .animated -->
	</div>
	<!-- .content -->

	<link href='{{asset('assets/css/fullcalendar.css')}}' rel='stylesheet'/>
	<link href='{{asset('assets/css/fullcalendar.print.css')}}' rel='stylesheet' media='print'/>


	<script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
	<script src="{{asset('vendors/popper.js/dist/umd/popper.min.js')}}"></script>
	<script src="{{asset('vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
	<script src="{{asset('assets/js/main.js')}}"></script>


	<script src='{{asset('assets/js/jquery-1.10.2.js')}}' type="text/javascript"></script>
	<script src='{{asset('assets/js/jquery-ui.custom.min.js')}}' type="text/javascript"></script>
	<script src='{{asset('assets/js/fullcalendar.js')}}' type="text/javascript"></script>



	<script>

		$(document).ready(function () {
var date = new Date();
var d = date.getDate();
var m = date.getMonth();
var y = date.getFullYear();

/*  className colors


            className: default(transparent), important(red), chill(pink), success(green), info(blue)

            */


/* initialize the external events
            -----------------------------------------------------------------*/

$('#external-events div.external-event').each(function () {

// create an Event Object (http://arshaw.com/fullcalendar/docs/event_data/Event_Object/)
// it doesn't need to have a start or end
var eventObject = {
title: $.trim($(this).text()) // use the element's text as the event title
};

// store the Event Object in the DOM element so we can get to it later
$(this).data('eventObject', eventObject);

// make the event draggable using jQuery UI
$(this).draggable({
zIndex: 999, revert: true, // will cause the event to go back to its
revertDuration: 0 // original position after the drag
});

});


/* initialize the calendar
            -----------------------------------------------------------------*/

var calendar = $('#calendar').fullCalendar({
header: {
left: 'title',
center: 'agendaDay,agendaWeek,month',
right: 'prev,next today'
},
editable: true,
firstDay: 1, // 1(Monday) this can be changed to 0(Sunday) for the USA system
selectable: true,
defaultView: 'month',

axisFormat: 'h:mm',
columnFormat: {
month: 'ddd', // Mon
week: 'ddd d', // Mon 7
day: 'dddd M/d', // Monday 9/7
agendaDay: 'dddd d'
},
titleFormat: {
month: 'MMMM yyyy', // September 2009
week: "MMMM yyyy", // September 2009
day: 'MMMM yyyy' // Tuesday, Sep 8, 2009
},
allDaySlot: false,
selectHelper: true,

droppable: true, // this allows things to be dropped onto the calendar !!!

events: [{% if is_granted('ROLE_WORKER_ADMIN') %}
{% for p, planning in plannings %}

{

title: '{{ planning.0.provider.name }}\n{{ planning.0.parkingId.name }}',

start: new Date("{{ planning.0.date|date('Y-m-d') }}T{{ planning.start }}"),
end: new Date("{{ planning.0.date|date('Y-m-d') }}T{{ planning.end }}"),
allDay: false,
className: 'info',
url: '{{ path("cleaner_detail", { 'id' : planning.0.id}) }}'
},{% endfor %}

{% else %}
{% for planning in plannings %}
{

title: '{{ planning.provider.name }}{% if planning.userCarId is not null %}{{ planning.userCarId.userHasCarNicknameCar }} {% endif %}',
start: new Date("{{ planning.PlannedCleaning.date|date('Y-m-d') }}T" + time_convert({{ planning.PlannedCleaning.plannedStart }})),
end: new Date("{{ planning.PlannedCleaning.date|date('Y-m-d') }}T" + time_convert({{ planning.PlannedCleaning.plannedEnd }})),
allDay: false,
className: 'info',
url: '{{ path("cleaner_detail", { 'id' : planning.PlannedCleaning.id}) }}'
},{% endfor %}
{% endif %}]
});

function time_convert(num) {
var hours = Math.floor(num / 60);
var minutes = num % 60;
return hours + ":" + minutes;
}

});
	</script>

{% endblock %}