src/Entity/Option.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OptionRepository")
 * @Orm\Table(name="`moovee_opt`")
 */
class Option
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Products", inversedBy="option")
     * @ORM\JoinColumn(nullable=false)
     */
    private $id_product;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CategoryOption", mappedBy="id_option", cascade={"merge", "persist"}, orphanRemoval=true)
     */
    private $category_option;

    /**
     * @ORM\Column(type="decimal", scale=2)
     */
    private $commission;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $supprime;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PlannedCleaningOptions", mappedBy="option_id")
     */
    private $plannedCleaningOptions;


    public function __construct()
    {
        $this->category_option = new ArrayCollection();
        $this->plannedCleaningOptions = new ArrayCollection();
    }




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdProduct(): ?Products
    {
        return $this->id_product;
    }

    public function setIdProduct(?Products $id_product): self
    {
        $this->id_product = $id_product;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    public function getCommission()
    {
        return $this->commission;
    }

    public function setCommission( $commission): self
    {
        $this->commission = $commission;

        return $this;
    }

    public function getSupprime(): ?int
    {
        return $this->supprime;
    }

    public function setSupprime(int $supprime): self
    {
        $this->supprime = $supprime;

        return $this;
    }

    /**
     * @return Collection|CategoryOption[]
     */
    public function getCategoryOption(): Collection
    {
        return $this->category_option;
    }

    public function addCategoryOption(CategoryOption $categoryOption): self
    {
        if (!$this->category_option->contains($categoryOption)) {
            $this->category_option[] = $categoryOption;
            $categoryOption->setIdOption($this);
        }

        return $this;
    }

    public function removeCategoryOption(CategoryOption $categoryOption): self
    {
        if ($this->category_option->contains($categoryOption)) {
            $this->category_option->removeElement($categoryOption);
            // set the owning side to null (unless already changed)
            if ($categoryOption->getIdOption() === $this) {
                $categoryOption->setIdOption(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PlannedCleaningOptions[]
     */
    public function getPlannedCleaningOptions(): Collection
    {
        return $this->plannedCleaningOptions;
    }

    public function addPlannedCleaningOption(PlannedCleaningOptions $plannedCleaningOption): self
    {
        if (!$this->plannedCleaningOptions->contains($plannedCleaningOption)) {
            $this->plannedCleaningOptions[] = $plannedCleaningOption;
            $plannedCleaningOption->setOptionId($this);
        }

        return $this;
    }

    public function removePlannedCleaningOption(PlannedCleaningOptions $plannedCleaningOption): self
    {
        if ($this->plannedCleaningOptions->contains($plannedCleaningOption)) {
            $this->plannedCleaningOptions->removeElement($plannedCleaningOption);
            // set the owning side to null (unless already changed)
            if ($plannedCleaningOption->getOptionId() === $this) {
                $plannedCleaningOption->setOptionId(null);
            }
        }

        return $this;
    }




}

src/Entity/Products.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductsRepository")
 */
class Products
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Option", mappedBy="id_product")
     */
    private $option;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CategoryProduct", mappedBy="id_product",cascade={"merge", "persist"}, orphanRemoval=true)
     */
    private $categoryProducts;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Provider", inversedBy="products")
     */
    private $id_provider;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categories", inversedBy="products")
     */
    private $categoryService;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $supprime;
    /**
     * @ORM\Column(type="decimal", scale=2)
     */
    private $commission;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PlannedCleaning", mappedBy="produit")
     */
    private $plannedCleanings;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $directBuy;


    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $autoValide;
    /**
     * @ORM\Column(type="string", nullable=true, length=255)
     * @Assert\File(mimeTypes={ "image/png", "image/jpg", "image/jpeg" })
     */
    private $photo;



    /**
     * @Assert\File(mimeTypes={ "image/png", "image/jpg", "image/jpeg" })
     */
    private $image;




    public function __construct()
    {
        $this->option = new ArrayCollection();
        $this->categoryProducts = new ArrayCollection();
        $this->plannedCleanings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    public function getCommission()
    {
        return $this->commission;
    }

    public function setCommission($commission): self
    {

        $this->commission = $commission;

        return $this;
    }
    public function getDirectBuy(): ?bool
    {
        return $this->directBuy;
    }

    public function setDirectBuy(?bool $directBuy): self
    {
        $this->directBuy = $directBuy;

        return $this;
    }


    public function getAutoValide(): ?bool
    {
        return $this->autoValide;
    }

    public function setAutoValide(?bool $autoValide): self
    {
        $this->autoValide = $autoValide;

        return $this;
    }
    public function getCategory(): ?Categories
    {
        return $this->categoryService;
    }

    public function setCategory(?Categories $categoryService): self
    {
        $this->categoryService = $categoryService;

        return $this;
    }
    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }


    /**
     * @return Collection|Option[]
     */
    public function getOption(): Collection
    {
        return $this->option;
    }

    public function addOption(Option $nameOption): self
    {
        if (!$this->option->contains($nameOption)) {
            $this->option[] = $nameOption;
            $nameOption->setIdProduct($this);
        }

        return $this;
    }

    public function removeNameOption(Option $nameOption): self
    {
        if ($this->option->contains($nameOption)) {
            $this->option->removeElement($nameOption);
            // set the owning side to null (unless already changed)
            if ($nameOption->getIdProduct() === $this) {
                $nameOption->setIdProduct(null);
            }
        }

        return $this;
    }


    public function getSupprime(): ?int
    {
        return $this->supprime;
    }

    public function setSupprime(int $supprime): self
    {
        $this->supprime = $supprime;

        return $this;
    }

    /**
     * @return Collection|CategoryProduct[]
     */
    public function getCategoryProducts(): Collection
    {
        return $this->categoryProducts;
    }
 
    public function addCategoryProduct(CategoryProduct $categoryProduct): self
    {
        if (!$this->categoryProducts->contains($categoryProduct)) {
            $this->categoryProducts[] = $categoryProduct;
            $categoryProduct->setIdProduct($this);
        }

        return $this;
    }

    public function removeCategoryProduct(CategoryProduct $categoryProduct): self
    {
        if ($this->categoryProducts->contains($categoryProduct)) {
            $this->categoryProducts->removeElement($categoryProduct);
            // set the owning side to null (unless already changed)
            if ($categoryProduct->getIdProduct() === $this) {
                $categoryProduct->setIdProduct(null);
            }
        }

        return $this;
    }



    public function getIdProvider(): ?Provider
    {
        return $this->id_provider;
    }

    public function setIdProvider(?Provider $id_provider): self
    {
        $this->id_provider = $id_provider;

        return $this;
    }

    /**
     * @return Collection|PlannedCleaning[]
     */
    public function getPlannedCleanings(): Collection
    {
        return $this->plannedCleanings;
    }

    public function addPlannedCleaning(PlannedCleaning $plannedCleaning): self
    {
        if (!$this->plannedCleanings->contains($plannedCleaning)) {
            $this->plannedCleanings[] = $plannedCleaning;
            $plannedCleaning->setProduit($this);
        }

        return $this;
    }

    public function removePlannedCleaning(PlannedCleaning $plannedCleaning): self
    {
        if ($this->plannedCleanings->contains($plannedCleaning)) {
            $this->plannedCleanings->removeElement($plannedCleaning);
            // set the owning side to null (unless already changed)
            if ($plannedCleaning->getProduit() === $this) {
                $plannedCleaning->setProduit(null);
            }
        }

        return $this;
    }
}

src/Form/OptionType.php
<?php


namespace App\Form;

use App\Entity\CategoryOption;
use App\Entity\MooveeUsers;
use App\Entity\Option;
use App\Entity\Products;
use App\Repository\ProductsRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PercentType;
use Symfony\Component\Form\Extension\Core\Type\TextType;


class OptionType extends AbstractType
{


    public function buildForm(FormBuilderInterface $builder, array $options){



        $builder
            ->add('name', TextType::class, array(
                'label' => "Name",


            ))
            ->add('description', TextareaType::class, array(
                'label' => "Description",


            ))
            ->add('commission', PercentType::class, array(
                'label' => "Commission",
                'scale' => 2,
                'type' => 'integer'

            ) )

            ->add('id_product', EntityType::class, array(
                'label' => "Product",
                'class' => Products::class,
                'query_builder' => function (ProductsRepository $er) {
                    return $er->createQueryBuilder('u')
                        ->leftJoin('u.id_provider', 'p')
                        ->where('u.supprime is Null')
                        ->andWhere('p.supprime is Null')
                        ->orderBy('u.name', 'ASC');
                },
                'choice_label' => "name",



            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Option::class,
        ]);
    }
}

templates/option/addcat.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette{% endblock %}

{% block content %}
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">

            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{{ path("cms_dashboard") }}">Dashboard</a></li>
                        <li><a href="{{ path("option_list") }}">Option</a></li>
                        <li><a href="{{ path("option_detail", {'id': option.id}) }}">{{ option.name }}</a></li>
                        <li class="active">Add Category Option</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content mt-3">
    <div class="animated fadeIn">
    <div class="row">

    <div class="col-md-12">
    <div class="card">
    <div class="card-header">
        <strong class="card-title">Add Category Option</strong>
    </div>
    <div class="card-body">
    <div class="tile col-lg-4" >
        {% for message in app.flashes('danger') %}
            <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show" role="alert">
                <span class="badge badge-pill badge-danger">Warning</span>
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}


        {{ form_start(form) }}
        <div class="form-group">
            {{ form_errors(form.category) }}
            {{ form_label(form.category) }}
            {{ form_widget(form.category, {'attr':{'class': 'form-control'  }}) }}
        </div>
        <div class="form-group">
            {{ form_errors(form.price) }}
            {{ form_label(form.price) }}
            {{ form_widget(form.price, {'attr':{'class': 'form-control'  }}) }}
        </div>

        <div class="form-group">
            {{ form_errors(form.time) }}
            {{ form_label(form.time) }}
            {{ form_widget(form.time, {'attr':{'class': 'form-control' }}) }}
        </div>



        <button type="submit" class="btn btn-info">Ajouter</button>
        <a href="{{ path("option_detail", {'id': option.id}) }}"  class="btn btn-danger">Retour</a>

        {{ form_end(form) }}

    </div>
    <script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
  	<script src="{{asset('vendors/popper.js/dist/umd/popper.min.js')}}"></script>
  	<script src="{{asset('vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
  	<script src="{{asset('assets/js/main.js')}}"></script>
{% endblock %}

templates/option/detail.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette
{% endblock %}

{% block content %}
	<div class="breadcrumbs">
		<div class="col-sm-4">
			<div class="page-header float-left"></div>
		</div>
		<div class="col-sm-8">
			<div class="page-header float-right">
				<div class="page-title">
					<ol class="breadcrumb text-right">
						<li>
							<a href="{{ path("cms_dashboard") }}">Dashboard</a>
						</li>
						<li>
							<a href="{{ path("option_list") }}">Option</a>
						</li>
						<li class="active">Detail Option</li>
					</ol>
				</div>
			</div>
		</div>
	</div>


	<div class="content mt-3">
		<div class="animated fadeIn">
			<div class="row">
				<div class="col-lg-4">
					<div class="card">
						<div class="card-header">
							<strong class="card-title">Description</strong>
						</div>
						<div class="card-body">

							<table class="table table-striped bordered">
								<tbody>
									<tr>
										<th>Option</th>
									</tr>
								</tbody>
							</td>
							<td>{{ option.name|capitalize }}</td>
						</tr>
						<tr>
							<th>Description</th>
						</tr>
					</td>
					<td>{{ option.description }}</td>
				</tr>
				<tr>
					<th>Product</th>
				</tr>
			</td>
			<td>{{ option.idProduct.name }}</td>
		</tr>
		<tr>
			<th>Commission</th>
			<td>{{ option.commission }}</td>
		</tr>

	</tbody>
</table>
<a href="{{ path("option_edit", {'id': option.id}) }}" class="btn btn-info">
	<i class="fa fa-pencil-square-o"></i>&nbsp;Modifier</a>
{% if is_granted('ROLE_AADMIN') %}
	<a onclick="return confirm('Do you want to delete the option {{ option.name }}?')" href="{{ path("option_delete", {'id': option.id}) }}" class="btn btn-danger">
		<i class="fa fa-trash-o"></i>&nbsp;Supprimer</a>
{% endif %}
<a href="{{ path("option_list") }}" class="btn btn-danger">Retour</a></div></div></div><div class="col-lg-8"><div class="card"><div class="card-header">
<strong class="card-title">Details Catégories</strong></div><div class="card-body">
{% for message in app.flashes('success') %}
	<div class="sufee-alert alert with-close alert-success alert-dismissible fade show" role="alert">
		<span class="badge badge-pill badge-success">Success</span>
		{{ message }}
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
{% endfor %}
<table class="table bordered">

	<thead style="background-color: #85A6B8; color: white;">
		<tr>
			<th>Catégorie</th>
			<th>Temps</th>
			<th>Prix</th>
			<th>
				<a href="{{ path("option_addcat", {'id': option.id}) }}" class="btn btn-success btn-sm">
					<i class="fa fa-plus mr-0"></i>&nbsp;Nouveau
				</a>
			</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			{% for categorie in option.categoryOption %}
				<td>{{ categorie.category }}</td>
				<td>{{ categorie.time }}
					minutes</td>
				<td>{{ categorie.price|number_format(2, '.', ',') }}
					€</td>
				<td>
					<a href="{{ path("option_editcat", {'idOp': option.id, 'idCat': categorie.id}) }}" class="btn btn-info btn-sm">
						<i class="fa fa-pencil"></i>
					</a>
					{% if is_granted('ROLE_AADMIN') %}
						<a onclick="return confirm('Do you want to delete this category?')" href="{{ path("option_deletecat", {'idOp': option.id, 'id': categorie.id}) }}" class="btn btn-danger btn-sm">
							<i class="fa fa-trash-o mr-0"></i>
						</a>
					{% endif %}

				</td>
			</tr>
		{% endfor %}
	</tbody>
</table></div></div></div></div></div></div>
<script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
<script src="{{asset('vendors/popper.js/dist/umd/popper.min.js')}}"></script>
<script src="{{asset('vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/main.js')}}"></script>{% endblock %}

templates/option/editcat.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette{% endblock %}

{% block content %}
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">

            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{{ path("cms_dashboard") }}">Dashboard</a></li>
                        <li><a href="{{ path("option_list") }}">Option</a></li>
                        <li><a href="{{ path("option_detail", {'id': option.id}) }}">{{ option.name }}</a></li>

                        <li class="active">Modifier Category Option</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content mt-3">
    <div class="animated fadeIn">
    <div class="row">

    <div class="col-md-12">
    <div class="card">
    <div class="card-header">
        <strong class="card-title">Modification Categorie Option</strong>
    </div>
    <div class="card-body">
    <div class="tile col-lg-4" >
        {% for message in app.flashes('danger') %}
            <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show" role="alert">
                <span class="badge badge-pill badge-danger">Warning</span>
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}


        {{ form_start(form) }}
        <div class="form-group">
            {{ form_errors(form.category) }}
            {{ form_label(form.category) }}
            {{ form_widget(form.category, {'attr':{'class': 'form-control'  }}) }}
        </div>
        <div class="form-group">
            {{ form_errors(form.price) }}
            {{ form_label(form.price) }}
            {{ form_widget(form.price, {'attr':{'class': 'form-control'  }}) }}
        </div>

        <div class="form-group">
            {{ form_errors(form.time) }}
            {{ form_label(form.time) }}
            {{ form_widget(form.time, {'attr':{'class': 'form-control' }}) }}
        </div>



        <button type="submit" class="btn btn-info">Modifier</button>
        <a href="{{ path("option_list") }}"  class="btn btn-danger">Retour</a>

        {{ form_end(form) }}

    </div>
    <script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
  	<script src="{{asset('vendors/popper.js/dist/umd/popper.min.js')}}"></script>
  	<script src="{{asset('vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
  	<script src="{{asset('assets/js/main.js')}}"></script>
{% endblock %}

templates/option/list.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette{% endblock %}

{% block content %}
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">

            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{{ path("cms_dashboard") }}">Dashboard</a></li>
                        <li class="active">Options</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content mt-3">
        <div class="animated fadeIn">
            <div class="row">

                <div class="col-md-12">
  
                        <div class="header">
                            <h4 style="text-align:center;">Option Manager</h4>
                        </div>
                        <div class="card-body">
                            {% for message in app.flashes('success') %}
                                <div class="sufee-alert alert with-close alert-success alert-dismissible fade show" role="alert">
                                    <span class="badge badge-pill badge-success">Success</span>
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                            <table id="bootstrap-data-table-export" class="table table-striped bordered">
                                <thead style="background-color: #85A6B8; color: white;">
                                <tr>
                                    <th>Cleaning Option Product</th>
                                    <th>Cleaning Option Title</th>
                                    <th>Cleaning Option Description</th>
                                    <th>Cleaning Option Commission</th>


                                    <th><a href="{{ path("option_add") }}" class="btn btn-success btn-sm">
                                            <i class="fa fa-plus mr-0"></i>&nbsp;Nouveau
                                        </a></th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for option in options %}
                                    {% if option.supprime is null %}
                                        <tr>
                                            <td>{{ option.idProduct.name }}</td>
                                            <td>{{ option.name }}</td>
                                            <td>{{ option.description }}</td>
                                            <td>{{ option.commission * 100}} % </td>

                                            <td><a href="{{ path("option_detail", {'id': option.id}) }}" class="btn btn-success btn-sm">
                                                    <i class="fa fa-eye mr-0"></i>
                                                </a>
                                                <a href="{{ path("option_edit", {'id': option.id}) }}" class="btn btn-info btn-sm">
                                                    <i class="fa fa-pencil mr-0"></i>
                                                </a>
                                                {% if is_granted('ROLE_ADMIN') %}
                                                <a onclick="return confirm('Do you want to delete the option {{ option.name }}?')" href="{{ path("option_delete", {'id': option.id}) }}" class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash-o mr-0"></i>
                                                </a>
                                                {% endif %}
                                                </td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div><!-- .animated -->
    </div><!-- .content -->

    <script src="../vendors/jquery/dist/jquery.min.js"></script>
    <script src="../vendors/popper.js/dist/umd/popper.min.js"></script>
    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../assets/js/main.js"></script>

    <script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
    <script src="../vendors/jszip/dist/jszip.min.js"></script>
    <script src="../vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="../vendors/pdfmake/build/vfs_fonts.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.colVis.min.js"></script>
    <script src="../assets/js/init-scripts/data-table/datatables-init.js"></script>

{% endblock %}