src/Entity/Products.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductsRepository")
 */
class Products
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Option", mappedBy="id_product")
     */
    private $option;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CategoryProduct", mappedBy="id_product",cascade={"merge", "persist"}, orphanRemoval=true)
     */
    private $categoryProducts;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Provider", inversedBy="products")
     */
    private $id_provider;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categories", inversedBy="products")
     */
    private $categoryService;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $supprime;
    /**
     * @ORM\Column(type="decimal", scale=2)
     */
    private $commission;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PlannedCleaning", mappedBy="produit")
     */
    private $plannedCleanings;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $directBuy;


    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $autoValide;
    /**
     * @ORM\Column(type="string", nullable=true, length=255)
     * @Assert\File(mimeTypes={ "image/png", "image/jpg", "image/jpeg" })
     */
    private $photo;



    /**
     * @Assert\File(mimeTypes={ "image/png", "image/jpg", "image/jpeg" })
     */
    private $image;




    public function __construct()
    {
        $this->option = new ArrayCollection();
        $this->categoryProducts = new ArrayCollection();
        $this->plannedCleanings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
    public function getCommission()
    {
        return $this->commission;
    }

    public function setCommission($commission): self
    {

        $this->commission = $commission;

        return $this;
    }
    public function getDirectBuy(): ?bool
    {
        return $this->directBuy;
    }

    public function setDirectBuy(?bool $directBuy): self
    {
        $this->directBuy = $directBuy;

        return $this;
    }


    public function getAutoValide(): ?bool
    {
        return $this->autoValide;
    }

    public function setAutoValide(?bool $autoValide): self
    {
        $this->autoValide = $autoValide;

        return $this;
    }
    public function getCategory(): ?Categories
    {
        return $this->categoryService;
    }

    public function setCategory(?Categories $categoryService): self
    {
        $this->categoryService = $categoryService;

        return $this;
    }
    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }
    public function getImage()
    {
        return $this->image;
    }

    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }


    /**
     * @return Collection|Option[]
     */
    public function getOption(): Collection
    {
        return $this->option;
    }

    public function addOption(Option $nameOption): self
    {
        if (!$this->option->contains($nameOption)) {
            $this->option[] = $nameOption;
            $nameOption->setIdProduct($this);
        }

        return $this;
    }

    public function removeNameOption(Option $nameOption): self
    {
        if ($this->option->contains($nameOption)) {
            $this->option->removeElement($nameOption);
            // set the owning side to null (unless already changed)
            if ($nameOption->getIdProduct() === $this) {
                $nameOption->setIdProduct(null);
            }
        }

        return $this;
    }


    public function getSupprime(): ?int
    {
        return $this->supprime;
    }

    public function setSupprime(int $supprime): self
    {
        $this->supprime = $supprime;

        return $this;
    }

    /**
     * @return Collection|CategoryProduct[]
     */
    public function getCategoryProducts(): Collection
    {
        return $this->categoryProducts;
    }
 
    public function addCategoryProduct(CategoryProduct $categoryProduct): self
    {
        if (!$this->categoryProducts->contains($categoryProduct)) {
            $this->categoryProducts[] = $categoryProduct;
            $categoryProduct->setIdProduct($this);
        }

        return $this;
    }

    public function removeCategoryProduct(CategoryProduct $categoryProduct): self
    {
        if ($this->categoryProducts->contains($categoryProduct)) {
            $this->categoryProducts->removeElement($categoryProduct);
            // set the owning side to null (unless already changed)
            if ($categoryProduct->getIdProduct() === $this) {
                $categoryProduct->setIdProduct(null);
            }
        }

        return $this;
    }



    public function getIdProvider(): ?Provider
    {
        return $this->id_provider;
    }

    public function setIdProvider(?Provider $id_provider): self
    {
        $this->id_provider = $id_provider;

        return $this;
    }

    /**
     * @return Collection|PlannedCleaning[]
     */
    public function getPlannedCleanings(): Collection
    {
        return $this->plannedCleanings;
    }

    public function addPlannedCleaning(PlannedCleaning $plannedCleaning): self
    {
        if (!$this->plannedCleanings->contains($plannedCleaning)) {
            $this->plannedCleanings[] = $plannedCleaning;
            $plannedCleaning->setProduit($this);
        }

        return $this;
    }

    public function removePlannedCleaning(PlannedCleaning $plannedCleaning): self
    {
        if ($this->plannedCleanings->contains($plannedCleaning)) {
            $this->plannedCleanings->removeElement($plannedCleaning);
            // set the owning side to null (unless already changed)
            if ($plannedCleaning->getProduit() === $this) {
                $plannedCleaning->setProduit(null);
            }
        }

        return $this;
    }
}

src/Entity/Provider.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProviderRepository")
 */
class Provider
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $tva;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Products", mappedBy="id_provider")
     */
    private $products;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $supprime;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\MooveeUsers", mappedBy="Provider")
     */
    private $mooveeUsers;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PlannedCleaning", mappedBy="Provider")
     */
    private $plannedCleanings;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $address2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $country;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Availability", mappedBy="provider")
     */
    private $availabilities;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CategoryProvider", mappedBy="id_provider")
     */
    private $providerCat;

 



    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->mooveeUsers = new ArrayCollection();
        $this->plannedCleanings = new ArrayCollection();
        $this->availabilities = new ArrayCollection();
        $this->parkingCat = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getTVA(): ?string
    {
        return $this->tva;
    }

    public function setTVA(string $tva): self
    {
        $this->tva = $tva;

        return $this;
    }

    public function getSupprime(): ?int
    {
        return $this->supprime;
    }

    public function setSupprime(int $supprime): self
    {
        $this->supprime = $supprime;

        return $this;
    }


    /**
     * @return Collection|Products[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Products $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->setIdProvider($this);
        }

        return $this;
    }

    public function removeProduct(Products $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            // set the owning side to null (unless already changed)
            if ($product->getIdProvider() === $this) {
                $product->setIdProvider(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|MooveeUsers[]
     */
    public function getMooveeUsers(): Collection
    {
        return $this->mooveeUsers;
    }

    public function addMooveeUser(MooveeUsers $mooveeUser): self
    {
        if (!$this->mooveeUsers->contains($mooveeUser)) {
            $this->mooveeUsers[] = $mooveeUser;
            $mooveeUser->setProvider($this);
        }

        return $this;
    }

    public function removeMooveeUser(MooveeUsers $mooveeUser): self
    {
        if ($this->mooveeUsers->contains($mooveeUser)) {
            $this->mooveeUsers->removeElement($mooveeUser);
            // set the owning side to null (unless already changed)
            if ($mooveeUser->getProvider() === $this) {
                $mooveeUser->setProvider(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|PlannedCleaning[]
     */
    public function getPlannedCleanings(): Collection
    {
        return $this->plannedCleanings;
    }

    public function addPlannedCleaning(PlannedCleaning $plannedCleaning): self
    {
        if (!$this->plannedCleanings->contains($plannedCleaning)) {
            $this->plannedCleanings[] = $plannedCleaning;
            $plannedCleaning->setProvider($this);
        }

        return $this;
    }

    public function removePlannedCleaning(PlannedCleaning $plannedCleaning): self
    {
        if ($this->plannedCleanings->contains($plannedCleaning)) {
            $this->plannedCleanings->removeElement($plannedCleaning);
            // set the owning side to null (unless already changed)
            if ($plannedCleaning->getProvider() === $this) {
                $plannedCleaning->setProvider(null);
            }
        }

        return $this;
    }

    public function getAddress2(): ?string
    {
        return $this->address2;
    }

    public function setAddress2(?string $address2): self
    {
        $this->address2 = $address2;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(?string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }


    /**
     * @return Collection|CategoryProvider[]
     */
    public function getCategoryProvider(): Collection
    {
      
            return $this->providerCat;
        
    }

    public function addCategoryProvider(CategoryProvider $providerCat): self
    {
        if (!$this->providerCat->contains($providerCat)) {
            $this->providerCat[] = $providerCat;
            $providerCat->setIdProvider($this);
        }

        return $this;
    }

    public function removeCategoryProvider(CategoryProvider $providerCat): self
    {
        if ($this->providerCat->contains($providerCat)) {
            $this->providerCat->removeElement($providerCat);
            // set the owning side to null (unless already changed)
            if ($providerCat->getIdProvider() === $this) {
                $providerCat->setIdProvider(null);
            }
        }

        return $this;
    }
    /**
     * @return Collection|Availability[]
     */
    public function getAvailabilities(): Collection
    {
        return $this->availabilities;
    }

    public function addAvailability(Availability $availability): self
    {
        if (!$this->availabilities->contains($availability)) {
            $this->availabilities[] = $availability;
            $availability->setProvider($this);
        }

        return $this;
    }

    public function removeAvailability(Availability $availability): self
    {
        if ($this->availabilities->contains($availability)) {
            $this->availabilities->removeElement($availability);
            // set the owning side to null (unless already changed)
            if ($availability->getProvider() === $this) {
                $availability->setProvider(null);
            }
        }

        return $this;
    }


    public function __toString()
    {
        return $this->name;
    }
}

src/Form/ProviderType.php
<?php


namespace App\Form;

use App\Entity\CategoryOption;
use App\Entity\MooveeUsers;
use App\Entity\Option;
use App\Entity\Products;
use App\Entity\Provider;
use Doctrine\Tests\Common\DataFixtures\TestEntity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;


class ProviderType extends AbstractType
{


    public function buildForm(FormBuilderInterface $builder, array $options){



        $builder
            ->add('name', TextType::class, array(
                'label' => "Name",


            ))
            ->add('address', TextType::class, array(
                'label' => "Address",


            ))
            ->add('address2', TextType::class, array(
                'label' => "Address 2",
                'required' => false,

            ))
            ->add('postal_code', TextType::class, array(
                'label' => "Postal Code",


            ))
            ->add('city', TextType::class, array(
                'label' => "City",


            ))
            ->add('country', TextType::class, array(
                'label' => "Country",


            ))
            ->add('tva', TextType::class, array(
                'label' => "Tva",


            ))

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Provider::class,
            'csrf_token_id' => 'login_form_csrf'
        ]);
    }
}

templates/provider/add.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette{% endblock %}

{% block content %}
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">

            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{{ path("cms_dashboard") }}">Dashboard</a></li>
                        <li><a href="{{ path("provider_list") }}">Provider</a></li>
                        <li class="active">Add Provider</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="content mt-3">
    <div class="animated fadeIn">
    <div class="row">

    <div class="col-md-12">
    <div class="card">
    <div class="card-header">
        <strong class="card-title">Add Provider</strong>
    </div>
    <div class="card-body">
    <div class="tile col-lg-4" >
        {% for message in app.flashes('danger') %}
            <div class="sufee-alert alert with-close alert-danger alert-dismissible fade show" role="alert">
                <span class="badge badge-pill badge-danger">Warning</span>
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}


        {{ form_start(form) }}
        <div class="form-group">
            {{ form_errors(form.name) }}
            {{ form_label(form.name) }}
            {{ form_widget(form.name, {'attr':{'class': 'form-control'  }}) }}
        </div>
        <div class="form-group">
            {{ form_errors(form.address) }}
            {{ form_label(form.address) }}
            {{ form_widget(form.address, {'attr':{'class': 'form-control'  }}) }}
        </div>

        <div class="form-group">
            {{ form_errors(form.tva) }}
            {{ form_label(form.tva) }}
            {{ form_widget(form.tva, {'attr':{'class': 'form-control' }}) }}
        </div>

        <div class="form-group">
            {{ form_errors(form.address2) }}
            {{ form_label(form.address2) }}
            {{ form_widget(form.address2, {'attr':{'class': 'form-control'  }}) }}
        </div>

        <div class="form-group">
            {{ form_errors(form.postal_code) }}
            {{ form_label(form.postal_code) }}
            {{ form_widget(form.postal_code, {'attr':{'class': 'form-control'  }}) }}
        </div>

        <div class="form-group">
            {{ form_errors(form.city) }}
            {{ form_label(form.city) }}
            {{ form_widget(form.city, {'attr':{'class': 'form-control'  }}) }}
        </div>
        <div class="form-group">
            {{ form_errors(form.country) }}
            {{ form_label(form.country) }}
            {{ form_widget(form.country, {'attr':{'class': 'form-control'  }}) }}
        </div>





        <button type="submit" class="btn btn-info">Add</button>
        <a href="{{ path("provider_list") }}"  class="btn btn-danger">Return</a>

        {{ form_end(form) }}

    </div>
    <script src="../../vendors/jquery/dist/jquery.min.js"></script>
    <script src="../../vendors/popper.js/dist/umd/popper.min.js"></script>
    <script src="../../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/main.js"></script>
{% endblock %}

templates/provider/detail.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette
{% endblock %}

{% block content %}
	<div class="breadcrumbs">
		<div class="col-sm-4">
			<div class="page-header float-left"></div>
		</div>
		<div class="col-sm-8">
			<div class="page-header float-right">
				<div class="page-title">
					<ol class="breadcrumb text-right">
						<li>
							<a href="{{ path("cms_dashboard") }}">Dashboard</a>
						</li>
						<li>
                        <a href="{{ path("provider_list") }}">Provider</a>

						</li>
						<li class="active">Detail Provider</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
<div class="content mt-3">
	<div class="animated fadeIn">
		<div class="row">
			<div class="col-lg-4">
				<div class="card">
					<div class="card-header">
						<strong class="card-title">Description</strong>
					</div>
					<div class="card-body">

						<table class="table table-striped bordered">
							<tbody>
								<tr>
									<td>Provider</td>
									<td>{{ provider.name|capitalize }}</td>
								</tr>
								<tr>
									<th>Address</th>
									<td>{{ provider.address|raw }}</td>
								</tr>
								<tr>
									<th>Address2</th>
									<td>{{ provider.address2|raw }}</td>
								</tr>
								<tr>
									<th>Postal Code</th>
									<td>{{ provider.postalCode|raw }}</td>
								</tr>
								<tr>
									<th>City</th>
									<td>{{ provider.city|raw }}</td>
								</tr>
								<tr>
									<th>Type</th>
									<td>{{ provider.country|raw }}</td>
								</tr>
								<tr>
									<th>Tva</th>
									<td>{{ provider.tva }}</td>
								</tr>
							</tbody>
						</table>
						<a href="{{ path("provider_edit", {'id': provider.id}) }}" class="btn btn-info">
							<i class="fa fa-pencil-square-o"></i>&nbsp;Modifier</a>

						<a onclick="return confirm('Do you want to delete the product {{ provider.name }}?')" href="{{ path("provider_delete", {'id': provider.id}) }}" class="btn btn-danger">
							<i class="fa fa-trash-o"></i>&nbsp;Delete</a>
						<a href="{{ path("provider_list") }}" class="btn btn-danger">Return</a>
					</div>
				</div>
			</div>
		<div class="col-lg-8">
		<div class="card">
		<div class="card-header">
			<strong class="card-title">Workers</strong>
		</div>

			<div class="card-body">
				{% for message in app.flashes('success') %}
					<div class="sufee-alert alert with-close alert-success alert-dismissible fade show" role="alert">
						<span class="badge badge-pill badge-success">Success</span>
						{{ message }}
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
					</div>
				{% endfor %}
			<table class="table table-striped table-bordered">
				<thead style="background-color: #85A6B8; color: white;">

					<tr>
						<th>First Name</th>
						<th>Last Name</th>
						<th>Role</th>
						<th>
						<a href="{{ path("provider_listdesworker", {'id': provider.id}) }}" class="btn btn-success btn-sm">
							<i class="fa fa-plus mr-0"></i>&nbsp;Add Workers
						</a>
						</th>

					</tr>
				</thead>
				<tbody>
					{% for client in clients %}
						<tr>
							<td>{{ client.firstName }}</td>
							<td>{{ client.lastName }}</td>
							<td>
								{% for item in client.roles %}
									{{ item }}
								{% endfor %}
							</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>

		</div>

<div class="col-lg-8">
	<div class="card">
<div class="card-header">
<strong class="card-title">Catégorie</strong>

</div>
		<div class="card-body">
			{% for message in app.flashes('success') %}
				<div class="sufee-alert alert with-close alert-success alert-dismissible fade show" role="alert">
					<span class="badge badge-pill badge-success">Success</span>
					{{ message }}
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
			{% endfor %}
				<table class="table table-striped table-bordered">
				<thead style="background-color: #85A6B8; color: white;">
					<tr>
						<th>Category</th>
						<th>
							<a href="{{ path("provider_addcatprovider", {'id': provider.id}) }}" class="btn btn-success btn-sm">
								<i class="fa fa-plus mr-0"></i>&nbsp;Add Category
							</a>
						</th>
					</tr>
				</thead>
				<tbody>
				{% for cat in catProvider %}
					<tr>
						<td>{{cat.idcategory.category}}
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>

		</div>
	</div>
</div>



	</div>
</div>
<script src="{{asset('vendors/jquery/dist/jquery.min.js')}}"></script>
<script src="{{asset('vendors/popper.js/dist/umd/popper.min.js')}}"></script>
<script src="{{asset('vendors/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{asset('assets/js/main.js')}}"></script>
{% endblock %}

templates/provider/list.html.twig
{% extends 'layoutadmin.html.twig' %}

{% block title %}Lucette{% endblock %}

{% block content %}
    <div class="breadcrumbs">
        <div class="col-sm-4">
            <div class="page-header float-left">

            </div>
        </div>
        <div class="col-sm-8">
            <div class="page-header float-right">
                <div class="page-title">
                    <ol class="breadcrumb text-right">
                        <li><a href="{{ path("cms_dashboard") }}">Dashboard</a></li>
                        <li class="active">Provider</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    <div class="content mt-3">
        <div class="animated fadeIn">
            <div class="row">

                <div class="col-md-12">
      
                        <div class="header">
                            <h4 style="text-align:center;">Provider Manager</h4>
                        </div>
                        <div class="card-body">
                            {% for message in app.flashes('success') %}
                                <div class="sufee-alert alert with-close alert-success alert-dismissible fade show" role="alert">
                                    <span class="badge badge-pill badge-success">Success</span>
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                            <table id="bootstrap-data-table-export" class="table table-striped bordered">
                                <thead style="background-color: #85A6B8; color: white;">
                                <tr>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>Address2</th>
                                    <th>Postal Code</th>
                                    <th>City</th>
                                    <th>Type</th>
                                    <th>Tva</th>

                                    <th><a href="{{ path("provider_add") }}" class="btn btn-success btn-sm">
                                            <i class="fa fa-plus mr-0"></i>&nbsp;Nouveau
                                        </a></th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for provider in providers %}
                                    {% if provider.supprime is null %}
                                        <tr>
                                            <td>{{ provider.name }}</td>
                                            <td>{{ provider.address }}</td>
                                            <td>{{ provider.address2 }}</td>
                                            <td>{{ provider.postalCode }}</td>
                                            <td>{{ provider.city }}</td>
                                            <td>{{ provider.country }}</td>
                                            <td>{{ provider.tva }}</td>
                                            <td>
                                                <a href="{{ path("provider_detail", {'id': provider.id}) }}" class="btn btn-success btn-sm">
                                                    <i class="fa fa-eye mr-0"></i>
                                                </a>

                                                <a href="{{ path("provider_edit", {'id': provider.id}) }}" class="btn btn-info btn-sm">
                                                    <i class="fa fa-pencil mr-0"></i>
                                                </a>
                                                <a onclick="return confirm('Do you want to delete the provider {{ provider.name }}?')" href="{{ path("provider_delete", {'id': provider.id}) }}" class="btn btn-danger btn-sm">
                                                    <i class="fa fa-trash-o mr-0"></i>
                                                </a></td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                                </tbody>

                            </table>
                        </div>
                    </div>
                </div>


            </div>
        </div><!-- .animated -->
    </div><!-- .content -->

    <script src="../vendors/jquery/dist/jquery.min.js"></script>
    <script src="../vendors/popper.js/dist/umd/popper.min.js"></script>
    <script src="../vendors/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="../assets/js/main.js"></script>

    <script src="../vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="../vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
    <script src="../vendors/jszip/dist/jszip.min.js"></script>
    <script src="../vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="../vendors/pdfmake/build/vfs_fonts.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="../vendors/datatables.net-buttons/js/buttons.colVis.min.js"></script>
    <script src="../assets/js/init-scripts/data-table/datatables-init.js"></script>

{% endblock %}